language: python
python:
    - "3.4"

# Docker testing
sudo: 9000 # 9000
dist: trusty

# Install dependencies
install:
    - "pip3 install --upgrade tox -r test-requirements.txt"

# Run tests
script: test.sh
